//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.17 at 05:29:08 PM IST 
//


package gov.loc.premis.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for copyrightInformationComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="copyrightInformationComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}copyrightStatus"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}copyrightJurisdiction"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}copyrightStatusDeterminationDate" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}copyrightNote" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}copyrightDocumentationIdentifier" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}copyrightApplicableDates" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "copyrightInformationComplexType", propOrder = {
    "copyrightStatus",
    "copyrightJurisdiction",
    "copyrightStatusDeterminationDate",
    "copyrightNote",
    "copyrightDocumentationIdentifier",
    "copyrightApplicableDates"
})
public class CopyrightInformationComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority copyrightStatus;
    @XmlElement(required = true)
    protected CountryCode copyrightJurisdiction;
    protected String copyrightStatusDeterminationDate;
    protected List<String> copyrightNote;
    protected List<CopyrightDocumentationIdentifierComplexType> copyrightDocumentationIdentifier;
    protected StartAndEndDateComplexType copyrightApplicableDates;

    /**
     * Gets the value of the copyrightStatus property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getCopyrightStatus() {
        return copyrightStatus;
    }

    /**
     * Sets the value of the copyrightStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setCopyrightStatus(StringPlusAuthority value) {
        this.copyrightStatus = value;
    }

    /**
     * Gets the value of the copyrightJurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCode }
     *     
     */
    public CountryCode getCopyrightJurisdiction() {
        return copyrightJurisdiction;
    }

    /**
     * Sets the value of the copyrightJurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCode }
     *     
     */
    public void setCopyrightJurisdiction(CountryCode value) {
        this.copyrightJurisdiction = value;
    }

    /**
     * Gets the value of the copyrightStatusDeterminationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyrightStatusDeterminationDate() {
        return copyrightStatusDeterminationDate;
    }

    /**
     * Sets the value of the copyrightStatusDeterminationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyrightStatusDeterminationDate(String value) {
        this.copyrightStatusDeterminationDate = value;
    }

    /**
     * Gets the value of the copyrightNote property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the copyrightNote property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCopyrightNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCopyrightNote() {
        if (copyrightNote == null) {
            copyrightNote = new ArrayList<String>();
        }
        return this.copyrightNote;
    }

    /**
     * Gets the value of the copyrightDocumentationIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the copyrightDocumentationIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCopyrightDocumentationIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CopyrightDocumentationIdentifierComplexType }
     * 
     * 
     */
    public List<CopyrightDocumentationIdentifierComplexType> getCopyrightDocumentationIdentifier() {
        if (copyrightDocumentationIdentifier == null) {
            copyrightDocumentationIdentifier = new ArrayList<CopyrightDocumentationIdentifierComplexType>();
        }
        return this.copyrightDocumentationIdentifier;
    }

    /**
     * Gets the value of the copyrightApplicableDates property.
     * 
     * @return
     *     possible object is
     *     {@link StartAndEndDateComplexType }
     *     
     */
    public StartAndEndDateComplexType getCopyrightApplicableDates() {
        return copyrightApplicableDates;
    }

    /**
     * Sets the value of the copyrightApplicableDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartAndEndDateComplexType }
     *     
     */
    public void setCopyrightApplicableDates(StartAndEndDateComplexType value) {
        this.copyrightApplicableDates = value;
    }

}
