//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.17 at 05:29:08 PM IST 
//


package gov.loc.premis.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for copyrightDocumentationIdentifierComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="copyrightDocumentationIdentifierComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}copyrightDocumentationIdentifierType"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}copyrightDocumentationIdentifierValue"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}copyrightDocumentationRole" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "copyrightDocumentationIdentifierComplexType", propOrder = {
    "copyrightDocumentationIdentifierType",
    "copyrightDocumentationIdentifierValue",
    "copyrightDocumentationRole"
})
public class CopyrightDocumentationIdentifierComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority copyrightDocumentationIdentifierType;
    @XmlElement(required = true)
    protected String copyrightDocumentationIdentifierValue;
    protected StringPlusAuthority copyrightDocumentationRole;

    /**
     * Gets the value of the copyrightDocumentationIdentifierType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getCopyrightDocumentationIdentifierType() {
        return copyrightDocumentationIdentifierType;
    }

    /**
     * Sets the value of the copyrightDocumentationIdentifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setCopyrightDocumentationIdentifierType(StringPlusAuthority value) {
        this.copyrightDocumentationIdentifierType = value;
    }

    /**
     * Gets the value of the copyrightDocumentationIdentifierValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCopyrightDocumentationIdentifierValue() {
        return copyrightDocumentationIdentifierValue;
    }

    /**
     * Sets the value of the copyrightDocumentationIdentifierValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCopyrightDocumentationIdentifierValue(String value) {
        this.copyrightDocumentationIdentifierValue = value;
    }

    /**
     * Gets the value of the copyrightDocumentationRole property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getCopyrightDocumentationRole() {
        return copyrightDocumentationRole;
    }

    /**
     * Sets the value of the copyrightDocumentationRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setCopyrightDocumentationRole(StringPlusAuthority value) {
        this.copyrightDocumentationRole = value;
    }

}
