//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.17 at 08:39:04 PM IST 
//


package gov.loc.premis.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for environmentFunctionComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="environmentFunctionComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}environmentFunctionType"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}environmentFunctionLevel"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "environmentFunctionComplexType", propOrder = {
    "environmentFunctionType",
    "environmentFunctionLevel"
})
public class EnvironmentFunctionComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority environmentFunctionType;
    @XmlElement(required = true)
    protected String environmentFunctionLevel;

    /**
     * Gets the value of the environmentFunctionType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getEnvironmentFunctionType() {
        return environmentFunctionType;
    }

    /**
     * Sets the value of the environmentFunctionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setEnvironmentFunctionType(StringPlusAuthority value) {
        this.environmentFunctionType = value;
    }

    /**
     * Gets the value of the environmentFunctionLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnvironmentFunctionLevel() {
        return environmentFunctionLevel;
    }

    /**
     * Sets the value of the environmentFunctionLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnvironmentFunctionLevel(String value) {
        this.environmentFunctionLevel = value;
    }

}
