//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.17 at 05:29:08 PM IST 
//


package gov.loc.premis.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for formatRegistryComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="formatRegistryComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}formatRegistryName"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}formatRegistryKey"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}formatRegistryRole" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="simpleLink" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "formatRegistryComplexType", propOrder = {
    "formatRegistryName",
    "formatRegistryKey",
    "formatRegistryRole"
})
public class FormatRegistryComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority formatRegistryName;
    @XmlElement(required = true)
    protected StringPlusAuthority formatRegistryKey;
    protected StringPlusAuthority formatRegistryRole;
    @XmlAttribute(name = "simpleLink")
    @XmlSchemaType(name = "anyURI")
    protected String simpleLink;

    /**
     * Gets the value of the formatRegistryName property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getFormatRegistryName() {
        return formatRegistryName;
    }

    /**
     * Sets the value of the formatRegistryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setFormatRegistryName(StringPlusAuthority value) {
        this.formatRegistryName = value;
    }

    /**
     * Gets the value of the formatRegistryKey property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getFormatRegistryKey() {
        return formatRegistryKey;
    }

    /**
     * Sets the value of the formatRegistryKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setFormatRegistryKey(StringPlusAuthority value) {
        this.formatRegistryKey = value;
    }

    /**
     * Gets the value of the formatRegistryRole property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getFormatRegistryRole() {
        return formatRegistryRole;
    }

    /**
     * Sets the value of the formatRegistryRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setFormatRegistryRole(StringPlusAuthority value) {
        this.formatRegistryRole = value;
    }

    /**
     * Gets the value of the simpleLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimpleLink() {
        return simpleLink;
    }

    /**
     * Sets the value of the simpleLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimpleLink(String value) {
        this.simpleLink = value;
    }

}
