//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.17 at 08:39:04 PM IST 
//


package gov.loc.premis.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for licenseDocumentationIdentifierComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="licenseDocumentationIdentifierComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}licenseDocumentationIdentifierType"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}licenseDocumentationIdentifierValue"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}licenseDocumentationRole" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "licenseDocumentationIdentifierComplexType", propOrder = {
    "licenseDocumentationIdentifierType",
    "licenseDocumentationIdentifierValue",
    "licenseDocumentationRole"
})
public class LicenseDocumentationIdentifierComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority licenseDocumentationIdentifierType;
    @XmlElement(required = true)
    protected String licenseDocumentationIdentifierValue;
    protected StringPlusAuthority licenseDocumentationRole;

    /**
     * Gets the value of the licenseDocumentationIdentifierType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getLicenseDocumentationIdentifierType() {
        return licenseDocumentationIdentifierType;
    }

    /**
     * Sets the value of the licenseDocumentationIdentifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setLicenseDocumentationIdentifierType(StringPlusAuthority value) {
        this.licenseDocumentationIdentifierType = value;
    }

    /**
     * Gets the value of the licenseDocumentationIdentifierValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseDocumentationIdentifierValue() {
        return licenseDocumentationIdentifierValue;
    }

    /**
     * Sets the value of the licenseDocumentationIdentifierValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseDocumentationIdentifierValue(String value) {
        this.licenseDocumentationIdentifierValue = value;
    }

    /**
     * Gets the value of the licenseDocumentationRole property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getLicenseDocumentationRole() {
        return licenseDocumentationRole;
    }

    /**
     * Sets the value of the licenseDocumentationRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setLicenseDocumentationRole(StringPlusAuthority value) {
        this.licenseDocumentationRole = value;
    }

}
