//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.17 at 10:12:53 AM IST 
//


package gov.loc.premis.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for linkingRightsStatementIdentifierComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="linkingRightsStatementIdentifierComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}linkingRightsStatementIdentifierType"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}linkingRightsStatementIdentifierValue"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="LinkPermissionStatementXmlID" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="simpleLink" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "linkingRightsStatementIdentifierComplexType", propOrder = {
    "linkingRightsStatementIdentifierType",
    "linkingRightsStatementIdentifierValue"
})
public class LinkingRightsStatementIdentifierComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority linkingRightsStatementIdentifierType;
    @XmlElement(required = true)
    protected String linkingRightsStatementIdentifierValue;
    @XmlAttribute(name = "LinkPermissionStatementXmlID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object linkPermissionStatementXmlID;
    @XmlAttribute(name = "simpleLink")
    @XmlSchemaType(name = "anyURI")
    protected String simpleLink;

    /**
     * Gets the value of the linkingRightsStatementIdentifierType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getLinkingRightsStatementIdentifierType() {
        return linkingRightsStatementIdentifierType;
    }

    /**
     * Sets the value of the linkingRightsStatementIdentifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setLinkingRightsStatementIdentifierType(StringPlusAuthority value) {
        this.linkingRightsStatementIdentifierType = value;
    }

    /**
     * Gets the value of the linkingRightsStatementIdentifierValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkingRightsStatementIdentifierValue() {
        return linkingRightsStatementIdentifierValue;
    }

    /**
     * Sets the value of the linkingRightsStatementIdentifierValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkingRightsStatementIdentifierValue(String value) {
        this.linkingRightsStatementIdentifierValue = value;
    }

    /**
     * Gets the value of the linkPermissionStatementXmlID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLinkPermissionStatementXmlID() {
        return linkPermissionStatementXmlID;
    }

    /**
     * Sets the value of the linkPermissionStatementXmlID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLinkPermissionStatementXmlID(Object value) {
        this.linkPermissionStatementXmlID = value;
    }

    /**
     * Gets the value of the simpleLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimpleLink() {
        return simpleLink;
    }

    /**
     * Sets the value of the simpleLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimpleLink(String value) {
        this.simpleLink = value;
    }

}
