//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.17 at 08:39:04 PM IST 
//


package gov.loc.premis.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for linkingAgentIdentifierComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="linkingAgentIdentifierComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}linkingAgentIdentifierType"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}linkingAgentIdentifierValue"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}linkingAgentRole" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="LinkAgentXmlID" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="simpleLink" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "linkingAgentIdentifierComplexType", propOrder = {
    "linkingAgentIdentifierType",
    "linkingAgentIdentifierValue",
    "linkingAgentRole"
})
public class LinkingAgentIdentifierComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority linkingAgentIdentifierType;
    @XmlElement(required = true)
    protected String linkingAgentIdentifierValue;
    protected List<StringPlusAuthority> linkingAgentRole;
    @XmlAttribute(name = "LinkAgentXmlID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object linkAgentXmlID;
    @XmlAttribute(name = "simpleLink")
    @XmlSchemaType(name = "anyURI")
    protected String simpleLink;

    /**
     * Gets the value of the linkingAgentIdentifierType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getLinkingAgentIdentifierType() {
        return linkingAgentIdentifierType;
    }

    /**
     * Sets the value of the linkingAgentIdentifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setLinkingAgentIdentifierType(StringPlusAuthority value) {
        this.linkingAgentIdentifierType = value;
    }

    /**
     * Gets the value of the linkingAgentIdentifierValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkingAgentIdentifierValue() {
        return linkingAgentIdentifierValue;
    }

    /**
     * Sets the value of the linkingAgentIdentifierValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkingAgentIdentifierValue(String value) {
        this.linkingAgentIdentifierValue = value;
    }

    /**
     * Gets the value of the linkingAgentRole property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkingAgentRole property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinkingAgentRole().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringPlusAuthority }
     * 
     * 
     */
    public List<StringPlusAuthority> getLinkingAgentRole() {
        if (linkingAgentRole == null) {
            linkingAgentRole = new ArrayList<StringPlusAuthority>();
        }
        return this.linkingAgentRole;
    }

    /**
     * Gets the value of the linkAgentXmlID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getLinkAgentXmlID() {
        return linkAgentXmlID;
    }

    /**
     * Sets the value of the linkAgentXmlID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setLinkAgentXmlID(Object value) {
        this.linkAgentXmlID = value;
    }

    /**
     * Gets the value of the simpleLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimpleLink() {
        return simpleLink;
    }

    /**
     * Sets the value of the simpleLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimpleLink(String value) {
        this.simpleLink = value;
    }

}
