//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.17 at 05:29:08 PM IST 
//


package gov.loc.premis.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for objectCharacteristicsComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="objectCharacteristicsComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}compositionLevel" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}fixity" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}size" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}format" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}creatingApplication" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}inhibitors" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}objectCharacteristicsExtension" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "objectCharacteristicsComplexType", propOrder = {
    "compositionLevel",
    "fixity",
    "size",
    "format",
    "creatingApplication",
    "inhibitors",
    "objectCharacteristicsExtension"
})
public class ObjectCharacteristicsComplexType {

    protected CompositionLevelComplexType compositionLevel;
    protected List<FixityComplexType> fixity;
    protected Long size;
    @XmlElement(required = true)
    protected List<FormatComplexType> format;
    protected List<CreatingApplicationComplexType> creatingApplication;
    protected List<InhibitorsComplexType> inhibitors;
    protected List<ExtensionComplexType> objectCharacteristicsExtension;

    /**
     * Gets the value of the compositionLevel property.
     * 
     * @return
     *     possible object is
     *     {@link CompositionLevelComplexType }
     *     
     */
    public CompositionLevelComplexType getCompositionLevel() {
        return compositionLevel;
    }

    /**
     * Sets the value of the compositionLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompositionLevelComplexType }
     *     
     */
    public void setCompositionLevel(CompositionLevelComplexType value) {
        this.compositionLevel = value;
    }

    /**
     * Gets the value of the fixity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fixity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFixity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FixityComplexType }
     * 
     * 
     */
    public List<FixityComplexType> getFixity() {
        if (fixity == null) {
            fixity = new ArrayList<FixityComplexType>();
        }
        return this.fixity;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSize(Long value) {
        this.size = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the format property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormatComplexType }
     * 
     * 
     */
    public List<FormatComplexType> getFormat() {
        if (format == null) {
            format = new ArrayList<FormatComplexType>();
        }
        return this.format;
    }

    /**
     * Gets the value of the creatingApplication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the creatingApplication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCreatingApplication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CreatingApplicationComplexType }
     * 
     * 
     */
    public List<CreatingApplicationComplexType> getCreatingApplication() {
        if (creatingApplication == null) {
            creatingApplication = new ArrayList<CreatingApplicationComplexType>();
        }
        return this.creatingApplication;
    }

    /**
     * Gets the value of the inhibitors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inhibitors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInhibitors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InhibitorsComplexType }
     * 
     * 
     */
    public List<InhibitorsComplexType> getInhibitors() {
        if (inhibitors == null) {
            inhibitors = new ArrayList<InhibitorsComplexType>();
        }
        return this.inhibitors;
    }

    /**
     * Gets the value of the objectCharacteristicsExtension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objectCharacteristicsExtension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjectCharacteristicsExtension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtensionComplexType }
     * 
     * 
     */
    public List<ExtensionComplexType> getObjectCharacteristicsExtension() {
        if (objectCharacteristicsExtension == null) {
            objectCharacteristicsExtension = new ArrayList<ExtensionComplexType>();
        }
        return this.objectCharacteristicsExtension;
    }

}
