//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.17 at 05:29:08 PM IST 
//


package gov.loc.premis.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for otherRightsDocumentationIdentifierComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="otherRightsDocumentationIdentifierComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}otherRightsDocumentationIdentifierType"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}otherRightsDocumentationIdentifierValue"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}otherRightsDocumentationRole" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "otherRightsDocumentationIdentifierComplexType", propOrder = {
    "otherRightsDocumentationIdentifierType",
    "otherRightsDocumentationIdentifierValue",
    "otherRightsDocumentationRole"
})
public class OtherRightsDocumentationIdentifierComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority otherRightsDocumentationIdentifierType;
    @XmlElement(required = true)
    protected String otherRightsDocumentationIdentifierValue;
    protected StringPlusAuthority otherRightsDocumentationRole;

    /**
     * Gets the value of the otherRightsDocumentationIdentifierType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getOtherRightsDocumentationIdentifierType() {
        return otherRightsDocumentationIdentifierType;
    }

    /**
     * Sets the value of the otherRightsDocumentationIdentifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setOtherRightsDocumentationIdentifierType(StringPlusAuthority value) {
        this.otherRightsDocumentationIdentifierType = value;
    }

    /**
     * Gets the value of the otherRightsDocumentationIdentifierValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherRightsDocumentationIdentifierValue() {
        return otherRightsDocumentationIdentifierValue;
    }

    /**
     * Sets the value of the otherRightsDocumentationIdentifierValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherRightsDocumentationIdentifierValue(String value) {
        this.otherRightsDocumentationIdentifierValue = value;
    }

    /**
     * Gets the value of the otherRightsDocumentationRole property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getOtherRightsDocumentationRole() {
        return otherRightsDocumentationRole;
    }

    /**
     * Sets the value of the otherRightsDocumentationRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setOtherRightsDocumentationRole(StringPlusAuthority value) {
        this.otherRightsDocumentationRole = value;
    }

}
