//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.17 at 10:12:53 AM IST 
//


package gov.loc.premis.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for otherRightsInformationComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="otherRightsInformationComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}otherRightsDocumentationIdentifier" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}otherRightsBasis"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}otherRightsApplicableDates" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}otherRightsNote" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "otherRightsInformationComplexType", propOrder = {
    "otherRightsDocumentationIdentifier",
    "otherRightsBasis",
    "otherRightsApplicableDates",
    "otherRightsNote"
})
public class OtherRightsInformationComplexType {

    protected List<OtherRightsDocumentationIdentifierComplexType> otherRightsDocumentationIdentifier;
    @XmlElement(required = true)
    protected StringPlusAuthority otherRightsBasis;
    protected StartAndEndDateComplexType otherRightsApplicableDates;
    protected List<String> otherRightsNote;

    /**
     * Gets the value of the otherRightsDocumentationIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherRightsDocumentationIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherRightsDocumentationIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OtherRightsDocumentationIdentifierComplexType }
     * 
     * 
     */
    public List<OtherRightsDocumentationIdentifierComplexType> getOtherRightsDocumentationIdentifier() {
        if (otherRightsDocumentationIdentifier == null) {
            otherRightsDocumentationIdentifier = new ArrayList<OtherRightsDocumentationIdentifierComplexType>();
        }
        return this.otherRightsDocumentationIdentifier;
    }

    /**
     * Gets the value of the otherRightsBasis property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getOtherRightsBasis() {
        return otherRightsBasis;
    }

    /**
     * Sets the value of the otherRightsBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setOtherRightsBasis(StringPlusAuthority value) {
        this.otherRightsBasis = value;
    }

    /**
     * Gets the value of the otherRightsApplicableDates property.
     * 
     * @return
     *     possible object is
     *     {@link StartAndEndDateComplexType }
     *     
     */
    public StartAndEndDateComplexType getOtherRightsApplicableDates() {
        return otherRightsApplicableDates;
    }

    /**
     * Sets the value of the otherRightsApplicableDates property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartAndEndDateComplexType }
     *     
     */
    public void setOtherRightsApplicableDates(StartAndEndDateComplexType value) {
        this.otherRightsApplicableDates = value;
    }

    /**
     * Gets the value of the otherRightsNote property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherRightsNote property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherRightsNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOtherRightsNote() {
        if (otherRightsNote == null) {
            otherRightsNote = new ArrayList<String>();
        }
        return this.otherRightsNote;
    }

}
