//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.17 at 05:29:08 PM IST 
//


package gov.loc.premis.v3;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relatedObjectIdentifierComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relatedObjectIdentifierComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}relatedObjectIdentifierType"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}relatedObjectIdentifierValue"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}relatedObjectSequence" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="RelObjectXmlID" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="simpleLink" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relatedObjectIdentifierComplexType", propOrder = {
    "relatedObjectIdentifierType",
    "relatedObjectIdentifierValue",
    "relatedObjectSequence"
})
public class RelatedObjectIdentifierComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority relatedObjectIdentifierType;
    @XmlElement(required = true)
    protected String relatedObjectIdentifierValue;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger relatedObjectSequence;
    @XmlAttribute(name = "RelObjectXmlID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object relObjectXmlID;
    @XmlAttribute(name = "simpleLink")
    @XmlSchemaType(name = "anyURI")
    protected String simpleLink;

    /**
     * Gets the value of the relatedObjectIdentifierType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getRelatedObjectIdentifierType() {
        return relatedObjectIdentifierType;
    }

    /**
     * Sets the value of the relatedObjectIdentifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setRelatedObjectIdentifierType(StringPlusAuthority value) {
        this.relatedObjectIdentifierType = value;
    }

    /**
     * Gets the value of the relatedObjectIdentifierValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedObjectIdentifierValue() {
        return relatedObjectIdentifierValue;
    }

    /**
     * Sets the value of the relatedObjectIdentifierValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedObjectIdentifierValue(String value) {
        this.relatedObjectIdentifierValue = value;
    }

    /**
     * Gets the value of the relatedObjectSequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRelatedObjectSequence() {
        return relatedObjectSequence;
    }

    /**
     * Sets the value of the relatedObjectSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRelatedObjectSequence(BigInteger value) {
        this.relatedObjectSequence = value;
    }

    /**
     * Gets the value of the relObjectXmlID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRelObjectXmlID() {
        return relObjectXmlID;
    }

    /**
     * Sets the value of the relObjectXmlID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRelObjectXmlID(Object value) {
        this.relObjectXmlID = value;
    }

    /**
     * Gets the value of the simpleLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimpleLink() {
        return simpleLink;
    }

    /**
     * Sets the value of the simpleLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimpleLink(String value) {
        this.simpleLink = value;
    }

}
