//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.17 at 10:12:53 AM IST 
//


package gov.loc.premis.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relationshipComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relationshipComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}relationshipType"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}relationshipSubType"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}relatedObjectIdentifier" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}relatedEventIdentifier" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}relatedEnvironmentPurpose" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}relatedEnvironmentCharacteristic" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relationshipComplexType", propOrder = {
    "relationshipType",
    "relationshipSubType",
    "relatedObjectIdentifier",
    "relatedEventIdentifier",
    "relatedEnvironmentPurpose",
    "relatedEnvironmentCharacteristic"
})
public class RelationshipComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority relationshipType;
    @XmlElement(required = true)
    protected StringPlusAuthority relationshipSubType;
    @XmlElement(required = true)
    protected List<RelatedObjectIdentifierComplexType> relatedObjectIdentifier;
    protected List<RelatedEventIdentifierComplexType> relatedEventIdentifier;
    protected List<StringPlusAuthority> relatedEnvironmentPurpose;
    protected StringPlusAuthority relatedEnvironmentCharacteristic;

    /**
     * Gets the value of the relationshipType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getRelationshipType() {
        return relationshipType;
    }

    /**
     * Sets the value of the relationshipType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setRelationshipType(StringPlusAuthority value) {
        this.relationshipType = value;
    }

    /**
     * Gets the value of the relationshipSubType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getRelationshipSubType() {
        return relationshipSubType;
    }

    /**
     * Sets the value of the relationshipSubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setRelationshipSubType(StringPlusAuthority value) {
        this.relationshipSubType = value;
    }

    /**
     * Gets the value of the relatedObjectIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedObjectIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedObjectIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedObjectIdentifierComplexType }
     * 
     * 
     */
    public List<RelatedObjectIdentifierComplexType> getRelatedObjectIdentifier() {
        if (relatedObjectIdentifier == null) {
            relatedObjectIdentifier = new ArrayList<RelatedObjectIdentifierComplexType>();
        }
        return this.relatedObjectIdentifier;
    }

    /**
     * Gets the value of the relatedEventIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedEventIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedEventIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RelatedEventIdentifierComplexType }
     * 
     * 
     */
    public List<RelatedEventIdentifierComplexType> getRelatedEventIdentifier() {
        if (relatedEventIdentifier == null) {
            relatedEventIdentifier = new ArrayList<RelatedEventIdentifierComplexType>();
        }
        return this.relatedEventIdentifier;
    }

    /**
     * Gets the value of the relatedEnvironmentPurpose property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the relatedEnvironmentPurpose property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRelatedEnvironmentPurpose().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringPlusAuthority }
     * 
     * 
     */
    public List<StringPlusAuthority> getRelatedEnvironmentPurpose() {
        if (relatedEnvironmentPurpose == null) {
            relatedEnvironmentPurpose = new ArrayList<StringPlusAuthority>();
        }
        return this.relatedEnvironmentPurpose;
    }

    /**
     * Gets the value of the relatedEnvironmentCharacteristic property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getRelatedEnvironmentCharacteristic() {
        return relatedEnvironmentCharacteristic;
    }

    /**
     * Sets the value of the relatedEnvironmentCharacteristic property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setRelatedEnvironmentCharacteristic(StringPlusAuthority value) {
        this.relatedEnvironmentCharacteristic = value;
    }

}
