//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.17 at 05:29:08 PM IST 
//


package gov.loc.premis.v3;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for relatedEventIdentifierComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="relatedEventIdentifierComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}relatedEventIdentifierType"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}relatedEventIdentifierValue"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}relatedEventSequence" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="RelEventXmlID" type="{http://www.w3.org/2001/XMLSchema}IDREF" /&gt;
 *       &lt;attribute name="simpleLink" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "relatedEventIdentifierComplexType", propOrder = {
    "relatedEventIdentifierType",
    "relatedEventIdentifierValue",
    "relatedEventSequence"
})
public class RelatedEventIdentifierComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority relatedEventIdentifierType;
    @XmlElement(required = true)
    protected String relatedEventIdentifierValue;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger relatedEventSequence;
    @XmlAttribute(name = "RelEventXmlID")
    @XmlIDREF
    @XmlSchemaType(name = "IDREF")
    protected Object relEventXmlID;
    @XmlAttribute(name = "simpleLink")
    @XmlSchemaType(name = "anyURI")
    protected String simpleLink;

    /**
     * Gets the value of the relatedEventIdentifierType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getRelatedEventIdentifierType() {
        return relatedEventIdentifierType;
    }

    /**
     * Sets the value of the relatedEventIdentifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setRelatedEventIdentifierType(StringPlusAuthority value) {
        this.relatedEventIdentifierType = value;
    }

    /**
     * Gets the value of the relatedEventIdentifierValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelatedEventIdentifierValue() {
        return relatedEventIdentifierValue;
    }

    /**
     * Sets the value of the relatedEventIdentifierValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelatedEventIdentifierValue(String value) {
        this.relatedEventIdentifierValue = value;
    }

    /**
     * Gets the value of the relatedEventSequence property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRelatedEventSequence() {
        return relatedEventSequence;
    }

    /**
     * Sets the value of the relatedEventSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRelatedEventSequence(BigInteger value) {
        this.relatedEventSequence = value;
    }

    /**
     * Gets the value of the relEventXmlID property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getRelEventXmlID() {
        return relEventXmlID;
    }

    /**
     * Sets the value of the relEventXmlID property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setRelEventXmlID(Object value) {
        this.relEventXmlID = value;
    }

    /**
     * Gets the value of the simpleLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSimpleLink() {
        return simpleLink;
    }

    /**
     * Sets the value of the simpleLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSimpleLink(String value) {
        this.simpleLink = value;
    }

}
