//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.17 at 05:29:08 PM IST 
//


package gov.loc.premis.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rightsStatementComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rightsStatementComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}rightsStatementIdentifier"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}rightsBasis"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}copyrightInformation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}licenseInformation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}statuteInformation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}otherRightsInformation" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}rightsGranted" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}linkingObjectIdentifier" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}linkingAgentIdentifier" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rightsStatementComplexType", propOrder = {
    "rightsStatementIdentifier",
    "rightsBasis",
    "copyrightInformation",
    "licenseInformation",
    "statuteInformation",
    "otherRightsInformation",
    "rightsGranted",
    "linkingObjectIdentifier",
    "linkingAgentIdentifier"
})
public class RightsStatementComplexType {

    @XmlElement(required = true)
    protected RightsStatementIdentifierComplexType rightsStatementIdentifier;
    @XmlElement(required = true)
    protected StringPlusAuthority rightsBasis;
    protected CopyrightInformationComplexType copyrightInformation;
    protected LicenseInformationComplexType licenseInformation;
    protected List<StatuteInformationComplexType> statuteInformation;
    protected OtherRightsInformationComplexType otherRightsInformation;
    protected List<RightsGrantedComplexType> rightsGranted;
    protected List<LinkingObjectIdentifierComplexType> linkingObjectIdentifier;
    protected List<LinkingAgentIdentifierComplexType> linkingAgentIdentifier;

    /**
     * Gets the value of the rightsStatementIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link RightsStatementIdentifierComplexType }
     *     
     */
    public RightsStatementIdentifierComplexType getRightsStatementIdentifier() {
        return rightsStatementIdentifier;
    }

    /**
     * Sets the value of the rightsStatementIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link RightsStatementIdentifierComplexType }
     *     
     */
    public void setRightsStatementIdentifier(RightsStatementIdentifierComplexType value) {
        this.rightsStatementIdentifier = value;
    }

    /**
     * Gets the value of the rightsBasis property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getRightsBasis() {
        return rightsBasis;
    }

    /**
     * Sets the value of the rightsBasis property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setRightsBasis(StringPlusAuthority value) {
        this.rightsBasis = value;
    }

    /**
     * Gets the value of the copyrightInformation property.
     * 
     * @return
     *     possible object is
     *     {@link CopyrightInformationComplexType }
     *     
     */
    public CopyrightInformationComplexType getCopyrightInformation() {
        return copyrightInformation;
    }

    /**
     * Sets the value of the copyrightInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CopyrightInformationComplexType }
     *     
     */
    public void setCopyrightInformation(CopyrightInformationComplexType value) {
        this.copyrightInformation = value;
    }

    /**
     * Gets the value of the licenseInformation property.
     * 
     * @return
     *     possible object is
     *     {@link LicenseInformationComplexType }
     *     
     */
    public LicenseInformationComplexType getLicenseInformation() {
        return licenseInformation;
    }

    /**
     * Sets the value of the licenseInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicenseInformationComplexType }
     *     
     */
    public void setLicenseInformation(LicenseInformationComplexType value) {
        this.licenseInformation = value;
    }

    /**
     * Gets the value of the statuteInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statuteInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatuteInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StatuteInformationComplexType }
     * 
     * 
     */
    public List<StatuteInformationComplexType> getStatuteInformation() {
        if (statuteInformation == null) {
            statuteInformation = new ArrayList<StatuteInformationComplexType>();
        }
        return this.statuteInformation;
    }

    /**
     * Gets the value of the otherRightsInformation property.
     * 
     * @return
     *     possible object is
     *     {@link OtherRightsInformationComplexType }
     *     
     */
    public OtherRightsInformationComplexType getOtherRightsInformation() {
        return otherRightsInformation;
    }

    /**
     * Sets the value of the otherRightsInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link OtherRightsInformationComplexType }
     *     
     */
    public void setOtherRightsInformation(OtherRightsInformationComplexType value) {
        this.otherRightsInformation = value;
    }

    /**
     * Gets the value of the rightsGranted property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rightsGranted property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRightsGranted().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RightsGrantedComplexType }
     * 
     * 
     */
    public List<RightsGrantedComplexType> getRightsGranted() {
        if (rightsGranted == null) {
            rightsGranted = new ArrayList<RightsGrantedComplexType>();
        }
        return this.rightsGranted;
    }

    /**
     * Gets the value of the linkingObjectIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkingObjectIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinkingObjectIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinkingObjectIdentifierComplexType }
     * 
     * 
     */
    public List<LinkingObjectIdentifierComplexType> getLinkingObjectIdentifier() {
        if (linkingObjectIdentifier == null) {
            linkingObjectIdentifier = new ArrayList<LinkingObjectIdentifierComplexType>();
        }
        return this.linkingObjectIdentifier;
    }

    /**
     * Gets the value of the linkingAgentIdentifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkingAgentIdentifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinkingAgentIdentifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LinkingAgentIdentifierComplexType }
     * 
     * 
     */
    public List<LinkingAgentIdentifierComplexType> getLinkingAgentIdentifier() {
        if (linkingAgentIdentifier == null) {
            linkingAgentIdentifier = new ArrayList<LinkingAgentIdentifierComplexType>();
        }
        return this.linkingAgentIdentifier;
    }

}
