//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.17 at 10:12:53 AM IST 
//


package gov.loc.premis.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for rightsGrantedComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="rightsGrantedComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}act"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}restriction" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}termOfGrant" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}termOfRestriction" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}rightsGrantedNote" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rightsGrantedComplexType", propOrder = {
    "act",
    "restriction",
    "termOfGrant",
    "termOfRestriction",
    "rightsGrantedNote"
})
public class RightsGrantedComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority act;
    protected List<StringPlusAuthority> restriction;
    protected StartAndEndDateComplexType termOfGrant;
    protected StartAndEndDateComplexType termOfRestriction;
    protected List<String> rightsGrantedNote;

    /**
     * Gets the value of the act property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getAct() {
        return act;
    }

    /**
     * Sets the value of the act property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setAct(StringPlusAuthority value) {
        this.act = value;
    }

    /**
     * Gets the value of the restriction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the restriction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRestriction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringPlusAuthority }
     * 
     * 
     */
    public List<StringPlusAuthority> getRestriction() {
        if (restriction == null) {
            restriction = new ArrayList<StringPlusAuthority>();
        }
        return this.restriction;
    }

    /**
     * Gets the value of the termOfGrant property.
     * 
     * @return
     *     possible object is
     *     {@link StartAndEndDateComplexType }
     *     
     */
    public StartAndEndDateComplexType getTermOfGrant() {
        return termOfGrant;
    }

    /**
     * Sets the value of the termOfGrant property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartAndEndDateComplexType }
     *     
     */
    public void setTermOfGrant(StartAndEndDateComplexType value) {
        this.termOfGrant = value;
    }

    /**
     * Gets the value of the termOfRestriction property.
     * 
     * @return
     *     possible object is
     *     {@link StartAndEndDateComplexType }
     *     
     */
    public StartAndEndDateComplexType getTermOfRestriction() {
        return termOfRestriction;
    }

    /**
     * Sets the value of the termOfRestriction property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartAndEndDateComplexType }
     *     
     */
    public void setTermOfRestriction(StartAndEndDateComplexType value) {
        this.termOfRestriction = value;
    }

    /**
     * Gets the value of the rightsGrantedNote property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rightsGrantedNote property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRightsGrantedNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getRightsGrantedNote() {
        if (rightsGrantedNote == null) {
            rightsGrantedNote = new ArrayList<String>();
        }
        return this.rightsGrantedNote;
    }

}
