//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.17 at 08:39:04 PM IST 
//


package gov.loc.premis.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for signatureComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="signatureComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}signatureEncoding"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}signer" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}signatureMethod"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}signatureValue"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}signatureValidationRules"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}signatureProperties" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}keyInformation" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "signatureComplexType", propOrder = {
    "signatureEncoding",
    "signer",
    "signatureMethod",
    "signatureValue",
    "signatureValidationRules",
    "signatureProperties",
    "keyInformation"
})
public class SignatureComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority signatureEncoding;
    protected StringPlusAuthority signer;
    @XmlElement(required = true)
    protected StringPlusAuthority signatureMethod;
    @XmlElement(required = true)
    protected String signatureValue;
    @XmlElement(required = true)
    protected StringPlusAuthority signatureValidationRules;
    protected List<String> signatureProperties;
    protected List<ExtensionComplexType> keyInformation;

    /**
     * Gets the value of the signatureEncoding property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getSignatureEncoding() {
        return signatureEncoding;
    }

    /**
     * Sets the value of the signatureEncoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setSignatureEncoding(StringPlusAuthority value) {
        this.signatureEncoding = value;
    }

    /**
     * Gets the value of the signer property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getSigner() {
        return signer;
    }

    /**
     * Sets the value of the signer property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setSigner(StringPlusAuthority value) {
        this.signer = value;
    }

    /**
     * Gets the value of the signatureMethod property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getSignatureMethod() {
        return signatureMethod;
    }

    /**
     * Sets the value of the signatureMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setSignatureMethod(StringPlusAuthority value) {
        this.signatureMethod = value;
    }

    /**
     * Gets the value of the signatureValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignatureValue() {
        return signatureValue;
    }

    /**
     * Sets the value of the signatureValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignatureValue(String value) {
        this.signatureValue = value;
    }

    /**
     * Gets the value of the signatureValidationRules property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getSignatureValidationRules() {
        return signatureValidationRules;
    }

    /**
     * Sets the value of the signatureValidationRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setSignatureValidationRules(StringPlusAuthority value) {
        this.signatureValidationRules = value;
    }

    /**
     * Gets the value of the signatureProperties property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the signatureProperties property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSignatureProperties().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSignatureProperties() {
        if (signatureProperties == null) {
            signatureProperties = new ArrayList<String>();
        }
        return this.signatureProperties;
    }

    /**
     * Gets the value of the keyInformation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the keyInformation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKeyInformation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtensionComplexType }
     * 
     * 
     */
    public List<ExtensionComplexType> getKeyInformation() {
        if (keyInformation == null) {
            keyInformation = new ArrayList<ExtensionComplexType>();
        }
        return this.keyInformation;
    }

}
