//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.09.17 at 08:39:04 PM IST 
//


package gov.loc.premis.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for statuteDocumentationIdentifierComplexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="statuteDocumentationIdentifierComplexType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}statuteDocumentationIdentifierType"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}statuteDocumentationIdentifierValue"/&gt;
 *         &lt;element ref="{http://www.loc.gov/premis/v3}statuteDocumentationRole" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "statuteDocumentationIdentifierComplexType", propOrder = {
    "statuteDocumentationIdentifierType",
    "statuteDocumentationIdentifierValue",
    "statuteDocumentationRole"
})
public class StatuteDocumentationIdentifierComplexType {

    @XmlElement(required = true)
    protected StringPlusAuthority statuteDocumentationIdentifierType;
    @XmlElement(required = true)
    protected String statuteDocumentationIdentifierValue;
    protected StringPlusAuthority statuteDocumentationRole;

    /**
     * Gets the value of the statuteDocumentationIdentifierType property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getStatuteDocumentationIdentifierType() {
        return statuteDocumentationIdentifierType;
    }

    /**
     * Sets the value of the statuteDocumentationIdentifierType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setStatuteDocumentationIdentifierType(StringPlusAuthority value) {
        this.statuteDocumentationIdentifierType = value;
    }

    /**
     * Gets the value of the statuteDocumentationIdentifierValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatuteDocumentationIdentifierValue() {
        return statuteDocumentationIdentifierValue;
    }

    /**
     * Sets the value of the statuteDocumentationIdentifierValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatuteDocumentationIdentifierValue(String value) {
        this.statuteDocumentationIdentifierValue = value;
    }

    /**
     * Gets the value of the statuteDocumentationRole property.
     * 
     * @return
     *     possible object is
     *     {@link StringPlusAuthority }
     *     
     */
    public StringPlusAuthority getStatuteDocumentationRole() {
        return statuteDocumentationRole;
    }

    /**
     * Sets the value of the statuteDocumentationRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringPlusAuthority }
     *     
     */
    public void setStatuteDocumentationRole(StringPlusAuthority value) {
        this.statuteDocumentationRole = value;
    }

}
